# Generated by Django 5.1.3 on 2025-11-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_customer_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Espèce'), ('CHEQUE', 'Chèque'), ('OTHER', 'Autre')], default='CASH', max_length=10, verbose_name='Méthode'),
        ),
    ]
