# Generated by Django 5.1.3 on 2025-11-20 12:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_stockmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Ouverture')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fermeture')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Fermée')),
                ('opening_counts', models.JSONField(default=dict, verbose_name='Comptage ouverture')),
                ('closing_counts', models.JSONField(blank=True, default=dict, null=True, verbose_name='Comptage fermeture')),
                ('opening_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Note ouverture')),
                ('closing_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Note fermeture')),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PAYMENT', 'Paiement'), ('ADJUST_IN', 'Ajustement +'), ('ADJUST_OUT', 'Ajustement -'), ('DROP', 'Remise de caisse'), ('COUNT', 'Comptage')], default='PAYMENT', max_length=16, verbose_name='Type')),
                ('method', models.CharField(blank=True, choices=[('CASH', 'Espèce'), ('CHEQUE', 'Chèque'), ('OTHER', 'Autre')], max_length=10, null=True, verbose_name='Méthode')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('counts_snapshot', models.JSONField(blank=True, help_text='Détail des billets/monnaies pour ce mouvement si pertinent', null=True, verbose_name='Comptage')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.payment', verbose_name='Paiement lié')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.sale', verbose_name='Vente liée')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='store.cashsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Mouvement de caisse',
                'verbose_name_plural': 'Mouvements de caisse',
                'ordering': ['-created_at'],
            },
        ),
    ]
