# Generated by Django 5.1.3 on 2025-11-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cashmovement_breakdowns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='movement_type',
            field=models.CharField(choices=[('PAYMENT', 'Paiement'), ('ADJUST_IN', 'Ajustement +'), ('ADJUST_OUT', 'Ajustement -'), ('DROP', 'Remise de caisse'), ('CHANGE', 'Rendu'), ('COUNT', 'Comptage')], default='PAYMENT', max_length=16, verbose_name='Type'),
        ),
    ]
